ucsb-cs148-w25/pj04-restaurantdecider

- team/Karthik.md
Add a markdown file for my introduction and project ideas.
> Add Karthik's ideas and introduction

- team/Chloe.md
Adds a file to team folder with Chloe's intro and project ideas.
> Chloe's Profile

- team/NORMS.md
Adds list of ideal behaviors under teams folder.
> Norms File

- README.md
Explains what the project is supposed to do. Also adds all the names and GitHub IDs of the team to the README, as outline here:
https://ucsb-cs148.github.io/w25/lectures/lect02/
> Add project description and members to README

- team/sprint01/lab02.md
Meeting notes from 1/17 section.
> lab02 Meeting Notes

- .gitignore
- server/app.js
- server/bin/www
- server/package.json
- server/routes/index.js
- server/routes/users.js
- server/yarn.lock
Initialize DuckDB in the `app.js` file and create a table `USERS` if it does not exist. Wrote some debug code to make sure the table actually exists.
Resolves #28
> Add DuckDB to Express Backend

- client/components.json
- client/package.json
- client/src/app.css
- client/src/lib/components/ui/button/button.svelte
- client/src/lib/components/ui/button/index.js
- client/src/lib/components/ui/input/index.js
- client/src/lib/components/ui/input/input.svelte
- client/src/lib/utils.js
- client/src/routes/login/+page.svelte
- client/src/routes/signup/+page.svelte
- client/tailwind.config.js
- client/yarn.lock
> Adding ShadCN / minor styling to login and signup

- client/src/lib/index.js
- client/src/routes/login/+page.svelte
- server/app.js
- server/package.json
- server/yarn.lock
Co-authored by: Chloe Weng chloeweng@ucsb.edu
Resolves issue #59. Creates login/signup forms that interface with the backend
Will need to load profile info into the store once the login API returns data + cookie
> Interface frontend login page with login and signup APIs

- server/app.js
- server/package.json
- server/routes/maps.js
- server/yarn.lock
Resolves issue #39 
Outputs list of restaurants given input parameters.
> Endpoint that outputs a list of restaurants given location and radius

- README.md
- client/.dockerignore
- client/Dockerfile
- client/package.json
- client/src/lib/index.js
- client/svelte.config.js
- client/yarn.lock
- docker-compose.yml
- server/.dockerignore
- server/Dockerfile
- server/app.js
- server/routes/maps.js
Added Docker to frontend and backend as well as corresponding instructions in the README.md.
To test, simply run `docker-compose up --build`.
> Dockerized Project

- client/src/lib/index.js
> Add /api to the api base url

- client/src/routes/restaurant_search/+page.svelte
This PR formats the /restaurant_search page with a card for the inputs and resizes the components on the page.
> Format Restaurant Search Page

- client/src/lib/stores/userStore.svelte.js
- client/src/routes/+page.svelte
- client/src/routes/bracket/+page.svelte
- client/src/routes/login/+page.svelte
- client/src/routes/restaurant_search/+page.svelte
- client/src/routes/signup/+page.svelte
- server/app.js
- server/package.json
- server/routes/authMiddleware.js
- server/routes/index.js
- server/routes/maps.js
- server/routes/users.js
- server/yarn.lock
> Migrate Username and Auth state to cookies

- server/app.js
- server/routes/ranking.js
> Ranking API endpoint.

- server/routes/maps.js
> Broaden filters for restaurant search

- server/app.js
> Change cors policy

- client/src/routes/restaurant_search/+page.svelte
> Add input validation

- client/src/routes/restaurant_search/+page.svelte
Completed ticket #94 
- Styled map
- Fixed dragging behavior
After consultation, decided to not move map to component as it will not be reused.
> Improved Map in Search Page

- client/src/routes/restaurant_search/+page.svelte
> Update upper limit of radius to 30.

- README.md
- client/src/routes/restaurant_search/+page.svelte
- server/routes/maps.js
This pull request is meant to allow users to select a place to eat, be it a coffee shop, restaurant, etc. A checkbox is added to the UI that displays each of these, and the user can select or deselect them to expand or restrict their search respectively.
> Add support for selecting restaurant types

- client/src/routes/bracket/+page.svelte
- client/src/routes/champion/+page.svelte
fixed the bug where restaurants weren't showing up in the ranking tournament
> bracketfix

- client/src/routes/profile/+page.svelte
Enlarges user greeting and puts it in the middle of the page.
> New Profile Page

- client/src/routes/+page.svelte
- client/src/routes/bracket/+page.svelte
- client/src/routes/champion/+page.svelte
- client/src/routes/homepage/+page.svelte
- client/src/routes/login/+page.svelte
- client/src/routes/profile/+page.svelte
- client/src/routes/restaurant_search/+page.svelte
- added a separate homepage (with the individual and team buttons) for after sign in and a homepage (with the sign in and sign up buttons) for before sign in
- if the user is signed in, then anytime they press the WEAT logo on the top left corner it redirects to the homepage with the individual and team buttons
- if the user is signed out, then anytime they press the WEAT logo on the top left corner it redirects to the homepage with the sign in and sign up buttons
> different homepage

- client/src/routes/restaurant_search/+page.server.js
Sets the default location to the location of the user's device instead of UCSB.
> Make default location the user's location instead of Isla Vista
